### ISSUE TITLE
"Gift of the Void" Name Conflict

### ISSUE THREAD

**Issue by fifguy85** [any2cards/jotl#1]
Looks like the Diviner and the Void Warden both have a card titled "Gift of the Void" and they render over the top of each other (in addition to both versions of the Diviner card) if you have both JOTL and Gloomhaven Card Viewer Extensions running (which you obviously would... ;D).

Example thread with the issue: https://boardgamegeek.com/thread/2462767/void-wardens-gift-void-card

**Comment by any2cards** [comment]
This is indeed an unfortunate situation, and one that I have been aware of; it's actually something I have discussed with Isaac.  It would be nice if their card names were unique across all of the different games; we even discussed them using some kind of database to track all of the names to avoid duplicates, and thus potential confusion.

Unfortunately, since the JCV and GCV are two different extensions, one is not aware of the other; this results is the overlay issue. There currently are only two solutions: first, you simply turn off one or the other viewer (depending on which one you actively need).  Not exactly convenient, but manageable.

The other solution would be to combine all of the viewers into one, so that a single name space is used, and thus at least all of the cards would be combined into a single display frame, so that they wouldn't be overlaid.  I am truly loathe to do this, as it has other implications.

I had reached out to several people to find someone with more knowledge than I when it comes to Javascript and CSS, as I wanted to create a feature that allows you to click on the extension icon, and quickly turn things on and/or off, but I have not received any responses as of yet.

**Comment by fifguy85** [comment]
Ah, yeah, that makes sense that the extensions wouldn't know about each other. I can also see how trying to combine the viewers would come with its own set of challenges. For now, I'll probably just pull up the Test pages to view the individual cards since those only apply to their own viewer (those are very helpful btw, so thanks for them!). Thanks for everything!
