### ISSUE TITLE
Question: future of this repository

### ISSUE THREAD

**Issue by joeskeen** [any2cards/jotl#3]
The readme notes:

> 11/10/2021: Only used for Firefox Add-On. The new Chrome Extension is powered by [Worldhaven Asset Viewer](https://github.com/any2cards/worldhaven).

Does this mean this repository is to be deprecated at some point in favor of Worldhaven, or will it continue to be maintained?

**Comment by any2cards** [comment]
That's a good question.  Ideally, Firefox would update their browser to support all of the calls that I am using to support Worldhaven within the Chrome Extension.  If they did, I could get rid of this repo, and use one set of code to support both browsers.

Just so you know, all of the assets found in the Gloomhavem, Jotl, and Frosthaven, repos also exist within the Worldhaven repo.  So if all you want is access to the assets, I would fork the Worldhaven repo.  The only reason these three still exist is so I can continue to support the GCV which the Firefox browsers uses, since I can't use the code from Worldhaven at the moment.
